spring:
  application:
    name: security-example

  security:
    user:
      name: nimesh
      password: 12345

  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_security
    username: root
    password: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
